server:
  port: 17002
eureka:
  instance:
    hostname: server1
  client:
    service-url:
      defaultZone: http://server2:17003/eureka/
spring:
  security:
    user:
      name: root
      password: 123456
  application:
    name: eurekanode




