server:
  port: 17001

spring:
  security:
    user:
      name: root
      password: 123456
#  profiles:
#    active: node1
  application:
    name: eurekamaster

eureka:
  instance:
    hostname: 192.168.1.167
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/




