server:
  port: 17024
  servlet:
    context-path: /ctm01scdemo1/serverconsumer4
spring:
  application:
    name: consumer4

eureka:
  client:
    service-url:
      defaultZone: http://root:123456@192.168.1.167:17001/eureka/
    healthcheck:
      enabled: true
